name: lexia
description: 'A new Flutter project.'
publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: ^0.20.2

  # UI
  flutter_svg: ^2.1.0
  flutter_screenutil: ^5.9.3
  toastification: ^3.0.2

  # network
  dio: ^5.8.0+1
  retrofit: ^4.5.0

  # data
  json_serializable: ^6.9.5
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3

  # DI
  injectable: ^2.5.0
  get_it: ^8.0.3

  # state
  flutter_bloc: ^9.1.1

  # util
  logging: ^1.3.0
  flutter_hooks: ^0.21.2
  synchronized: ^3.3.1
  uuid: ^4.5.1
  flutter_dotenv: ^5.2.1
  collection: ^1.19.1

  global_navigator:
    git:
      url: https://github.com/kume1a/flutter_global_navigator.git
  common_utilities:
    git:
      url: https://github.com/kume1a/flutter_common.git
      path: packages/common_utilities
  common_widgets:
    git:
      url: https://github.com/kume1a/flutter_common.git
      path: packages/common_widgets
  common_models:
    git:
      url: https://github.com/kume1a/flutter_common.git
      path: packages/common_models
  common_network_components:
    git:
      url: https://github.com/kume1a/flutter_common.git
      path: packages/common_network_components

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.15
  flutter_lints: ^6.0.0
  freezed: ^2.5.8
  injectable_generator: ^2.7.0
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.3
  retrofit_generator: ^9.3.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - env/
    - assets/
    - assets/icons/
    - assets/logo/
    - assets/images/

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/logo/logo.png'
  image_path_android: 'assets/logo/logo_transparent_bg.png'
  min_sdk_android: 21

  remove_alpha_ios: true
  adaptive_icon_background: '#ffffff'

flutter_native_splash:
  color: '#ffffff'
  image: assets/logo/logo_1152.png

  android_gravity: center
  ios_content_mode: scaleAspectFit
  web_image_mode: contain

  android_12:
    image: assets/logo/logo_960.png
    color: '#ffffff'
    icon_background_color: '#ffffff'
